eval "$(starship init zsh)"

alias gf="git fetch"
alias grb="git rebase"
alias ga="git add"
alias gst="git status"
alias gc="git commit"
alias gco="git checkout"
alias gp="git push"
alias gfgrb="git fetch && git rebase"
alias gs="git stash"
alias gsp="git stash pop"

alias ll="eza --git --long --group --icons=auto --group-directories-first --all"
alias config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
alias zconfig="code ~/.zshrc"
