# Persistent "NovaMedia" virtual sink for music/videos/browser
# NovaGame and NovaChat sinks are managed by the nova-chatmix service
context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "NovaMedia"
            capture.props = {
                media.class    = Audio/Sink
                node.name      = NovaMedia
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name      = nova-media-output
                audio.position = [ FL FR ]
            }
        }
    }
]
