# Rename Electron apps that show up as "Chromium" in pavucontrol
# Add more blocks here for other Electron apps as needed
pulse.rules = [
    {
        matches = [ { application.process.binary = "Cider" } ]
        actions = {
            update-props = {
                application.name = "Cider"
                application.icon_name = "cider"
            }
        }
    }
]
