-- Hyprland 0.56+ Lua config. Ported from hyprland.conf (hyprlang) after 0.56
-- dropped hyprlang support. API reference: /usr/share/hypr/stubs/hl.meta.lua

local HOME = os.getenv("HOME")
local CYBR = HOME .. "/.local/share/cybrdots/cybr-hyprland"

-- ── CYBR theme (upstream cybr-hyprland cache) ──
-- Upstream is hyprlang-only and frozen at Hyprland 0.54 (see its readme), so the
-- palette is parsed out of its vars.conf here and theme.conf is mirrored in Lua
-- below. Palette updates still flow in via: git -C <cache> pull

local function parse_vars(path)
    local vars = {}
    local f = io.open(path, "r")
    if not f then return vars end
    for line in f:lines() do
        local k, v = line:match("^%s*%$([%w_]+)%s*=%s*(.-)%s*$")
        if k then
            vars[k] = (v:gsub("%s*#.*$", ""))
        end
    end
    f:close()
    return vars
end

local V = parse_vars(CYBR .. "/vars.conf")
local function num(k, fallback) return tonumber(V[k]) or fallback end
local function rgba(color, alpha) return "rgba(" .. (color or "ffffff") .. (alpha or "FF") .. ")" end

-- Mirror of theme.conf (decoration/group/groupbar)
hl.config({
    general = {
        border_size = num("border", 1),
        col = {
            inactive_border = rgba(V.cy0, V.tr0),
            active_border   = rgba(V.re0, V.trF),
        },
        gaps_in  = num("gapS", 4),
        gaps_out = num("gapM", 8),
    },

    decoration = {
        rounding       = num("radius", 28),
        rounding_power = num("power", 1.0),

        active_opacity   = num("activeTr", 1),
        inactive_opacity = num("inActiveTr", 1),

        blur = {
            enabled           = true,
            size              = num("blurSize", 6),
            passes            = num("blurPass", 4),
            noise             = num("noise", 0.05),
            ignore_opacity    = true,
            new_optimizations = true,
            xray              = false,
            popups            = true,
        },

        shadow = {
            enabled        = true,
            range          = 30,
            scale          = 2,
            render_power   = 5,
            color          = rgba(V.re0, V.tr2),
            color_inactive = rgba(V.no0, V.tr2),
        },

        dim_inactive = false,
        dim_strength = 1,
        dim_special  = 0,
    },

    group = {
        col = {
            border_active          = rgba(V.re0, V.trF),
            border_inactive        = rgba(V.re1, V.trF),
            border_locked_active   = rgba(V.vi0, V.trF),
            border_locked_inactive = rgba(V.vi0, V.tr7),
        },

        groupbar = {
            col = {
                active          = rgba(V.re0, V.trF),
                inactive        = rgba(V.re1, V.trF),
                locked_active   = rgba(V.vi0, V.trF),
                locked_inactive = rgba(V.vi0, V.tr7),
            },
            font_size        = num("fontM", 12),
            text_color       = rgba(V.no0, V.trF),
            height           = 1,
            indicator_height = 24,
            text_offset      = -12,
        },
    },
})

-- ── Animations (my overrides; upstream theme disables them) ──
hl.config({ animations = { enabled = true } })
hl.curve("snappy", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
hl.animation({ leaf = "windows",    enabled = true, speed = 4, bezier = "snappy" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "snappy", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 6, bezier = "snappy" })
hl.animation({ leaf = "fade",       enabled = true, speed = 4, bezier = "snappy" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "snappy" })

-- ── Monitors ──
-- monitors.lua is generated by nwg-displays. It doesn't know about HDR/color
-- management, so DP-5 is re-declared here with the HDR bits (last write wins).
dofile(HOME .. "/.config/hypr/monitors.lua")
hl.monitor({
    output        = "DP-5",
    mode          = "2560x1440@279.96",
    position      = "0x0",
    scale         = 1.0,
    bitdepth      = 10,
    cm            = "hdr",
    sdrbrightness = 2.0,
    sdrsaturation = 1.2,
})

-- ── Environment ──
-- Point the whole session at the persistent systemd ssh-agent (ssh-agent.service,
-- socket -a $XDG_RUNTIME_DIR/ssh-agent.socket). SDDM -> start-hyprland doesn't import
-- the systemd user env, and per-shell exports (fish conf.d) don't reach non-fish
-- children like the bash the Claude Code harness spawns. Setting it here makes EVERY
-- session process inherit one consistent socket. UID 1000 is fixed on this box.
hl.env("SSH_AUTH_SOCK", "/run/user/1000/ssh-agent.socket")

-- NVIDIA Wayland — explicit driver selection + direct video decode backend
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")

-- NVIDIA shader disk cache — default 1GB limit makes the driver prune Overwatch 2's
-- ~8GB compiled-shader cache on every launch, forcing a 20-30min recompile each time.
-- Must be global (not Steam launch options): Steam's background fossilize replay runs
-- under Steam's env and would still trim the cache otherwise.
hl.env("__GL_SHADER_DISK_CACHE_SIZE", "21474836480")
hl.env("__GL_SHADER_DISK_CACHE_SKIP_CLEANUP", "1")

hl.config({
    misc = {
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
    },
    render = {
        cm_auto_hdr = 2,
    },
})

-- ── Programs ──
local mainMod     = "SUPER"
local terminal    = "ghostty"
local fileManager = "thunar"
local menu        = "rofi -show run"
local scripts     = HOME .. "/.config/hypr/scripts"

-- ── Keybindings ──
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + TAB", hl.dsp.window.cycle_next())
hl.bind(mainMod .. " + TAB", hl.dsp.window.bring_to_top())
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(scripts .. "/smart-fullscreen.sh maximize"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(scripts .. "/smart-fullscreen.sh fullscreen"))
hl.bind("Print", hl.dsp.exec_cmd(scripts .. "/hypr-screenshot.sh fullscreen"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(scripts .. "/hypr-screenshot.sh area"))

hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("vicinae toggle"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))

-- ── Scratchpad ("minimize") ──
-- Stash the focused window in a hidden special workspace…
-- (silent = move the window away WITHOUT following it, so your view stays put)
hl.bind(mainMod .. " + H", hl.dsp.window.move({ workspace = "special:hidden", silent = true }))
-- …and toggle that scratchpad into/out of view to get windows back.
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.workspace.toggle_special("hidden"))
-- Toggle the "minimized" scratchpad (windows sent there via the titlebar button).
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.workspace.toggle_special("minimized"))

-- ── Workspaces ──
-- Ported from the macOS AeroSpace config: numbered + letter-named workspaces,
-- each pinned to a monitor, with apps auto-routed to their workspace. The two
-- rule sections that follow do the monitor pinning and the app assignment.

-- ALT + {n}: switch to workspace n; ALT + SHIFT + {n}: move focused window there
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind("ALT + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind("ALT + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- ALT + {letter}: the mnemonic workspaces (W=web, C=code, T=term, S=slack, …)
local namedWorkspaces = { "C", "F", "L", "M", "N", "P", "S", "T", "W" }
for _, ws in ipairs(namedWorkspaces) do
    hl.bind("ALT + " .. ws, hl.dsp.focus({ workspace = "name:" .. ws }))
    hl.bind("ALT + SHIFT + " .. ws, hl.dsp.window.move({ workspace = "name:" .. ws }))
end

-- i3-style directional focus / move (AeroSpace's ctrl-alt-hjkl). h/j/k/l = ←/↓/↑/→
for key, dir in pairs({ H = "l", J = "d", K = "u", L = "r" }) do
    hl.bind("CTRL + ALT + " .. key, hl.dsp.focus({ direction = dir }))
    hl.bind("CTRL + ALT + SHIFT + " .. key, hl.dsp.window.move({ direction = dir }))
end

-- preserve_split makes CTRL+ALT+E (togglesplit) actually take effect: without it,
-- dwindle re-picks split orientation from window shape on every change and instantly
-- overrides the toggle. On = splits stay where you put them (predictable, i3-like).
hl.config({ dwindle = { preserve_split = true } })

-- Layout / mode toggles (AeroSpace's ctrl-alt-{f,e,enter}). AeroSpace's
-- ctrl-alt-a (accordion) is dropped: Hyprland's only analog is window groups
-- (a tabbed container with a title bar across the top), which isn't what that did.
hl.bind("CTRL + ALT + F", hl.dsp.window.fullscreen({ mode = 0 }))          -- true fullscreen
hl.bind("CTRL + ALT + E", hl.dsp.layout("togglesplit"))                    -- flip side-by-side ↔ stacked
hl.bind("CTRL + ALT + RETURN", hl.dsp.window.float({ action = "toggle" })) -- float ↔ tile (also on SUPER+V)

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })

-- ── Workspace → monitor (AeroSpace workspace-to-monitor-force-assignment) ──
-- DP-5   = Gigabyte MO27Q28G (OLED) — this was "main"/"MO27Q28G" on the Mac.
-- HDMI-A-2 = Lenovo G27c-10  (IPS)  — this was "secondary" on the Mac.
-- The Mac had three monitor identities (main / secondary / MO27Q28G); they
-- collapse onto two screens here, so "main" and "MO27Q28G" both land on the OLED.
-- To move a workspace to the other screen, just change its monitor below.
local OLED = "DP-5"
local IPS  = "HDMI-A-2"
local wsMonitor = {
    ["1"] = OLED, ["7"] = OLED, ["8"] = OLED, ["9"] = OLED, ["10"] = OLED,
    ["2"] = IPS,  ["3"] = IPS,  ["4"] = IPS,  ["5"] = IPS,  ["6"]  = IPS,
    ["name:C"] = OLED, ["name:W"] = OLED, ["name:M"] = OLED,
    -- F, L, N, P, S, T were unpinned on the Mac → they open on the focused monitor
}
for ws, mon in pairs(wsMonitor) do
    hl.workspace_rule({ workspace = ws, monitor = mon })
end

-- ── App → workspace (AeroSpace on-window-detected) ──
-- The declarative `hl.window_rule{match=…}` API doesn't route windows on this
-- 0.56 build, so this mirrors AeroSpace's on-window-detected directly: on every
-- window open, look up its class and move it to the mnemonic workspace.
--   ws     = target workspace ("name:X" for letters, or a number as a string)
--   follow = true  → jump to that workspace with the window (--focus-follows-window)
--            false → move it there silently, leaving your view where it is
-- Class is the Wayland app class; find it with `hyprctl clients | grep class`.
local appWorkspace = {
    ["firefox"]               = { ws = "name:W", follow = true  }, -- browser (was Arc/Safari)
    ["Cursor"]                = { ws = "name:C", follow = true  }, -- editor
    ["com.mitchellh.ghostty"] = { ws = "name:T", follow = true  }, -- terminal
    ["obsidian"]              = { ws = "name:N", follow = true  }, -- notes
    ["Slack"]                 = { ws = "name:S", follow = true  }, -- chat
    -- Apps below have no native Linux build / unknown class yet — open the app,
    -- grab its class from `hyprctl clients`, drop it in on the left, and uncomment:
    -- ["Linear"]             = { ws = "name:P", follow = true  }, -- Linear
    -- ["<calendar class>"]   = { ws = "9",      follow = false }, -- calendar (was Cron)
    -- ["<music class>"]      = { ws = "8",      follow = false }, -- music (was Apple Music)
    -- ["<claude class>"]     = { ws = "10",     follow = true  }, -- Claude desktop
}

-- win is an HL.Window userdata (not a plain table), and it isn't focused yet at
-- open time — so match on win.class and move that exact window by its address.
hl.on("window.open", function(win)
    if not win then return end
    local rule = appWorkspace[win.class] or appWorkspace[win.initial_class]
    if not rule then return end
    hl.dispatch(hl.dsp.window.move({
        workspace = rule.ws,
        window    = "address:" .. win.address,
        silent    = not rule.follow,
    }))
end)

-- Finder floated on the Mac → float the file manager (thunar) when it opens.
hl.on("window.open", function(win)
    if win and (win.class or ""):match("[Tt]hunar") then
        hl.dispatch(hl.dsp.window.float({ action = "enable", window = "address:" .. win.address }))
    end
end)

-- ── Autostart ──
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar") -- upstream cybr-waybar launches plainly (see ~/.config/waybar -> cache)
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("systemctl --user start vicinae.service")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(scripts .. "/load-hyprbars.sh")
    hl.exec_cmd(scripts .. "/nte-window-keeper.sh")
    hl.exec_cmd(scripts .. "/xwayland-primary-monitor.sh DP-5")
    hl.exec_cmd(HOME .. "/.local/bin/set-wallpaper --restore")
end)

-- ── hyprbars: titlebars ──
-- Plugin config keys/functions only exist while the plugin is loaded, and
-- hl.plugin.load() is async — so the plugin is loaded by load-hyprbars.sh
-- (autostart above), which then re-runs `hyprctl reload` to land back here
-- with hyprbars available. On a plain reload it's already loaded.
local barsLoaded = false
for _, p in ipairs(hl.get_loaded_plugins() or {}) do
    if p.name == "hyprbars" then barsLoaded = true end
end

if barsLoaded then
    hl.config({
        plugin = {
            hyprbars = {
                bar_height = 28,
                bar_color  = "rgb(" .. V.no0 .. ")", -- CYBR background
                col        = { text = "rgb(" .. V.wh0 .. ")" }, -- CYBR foreground
                bar_text_font              = "GeistMono NF",
                bar_text_size              = 14,
                bar_text_align             = "left",
                bar_buttons_alignment      = "left",
                bar_padding                = 16, -- horizontal inset (leading offset of the button group)
                bar_button_padding         = 8,  -- spacing between the buttons
                bar_part_of_window         = true,
                bar_precedence_over_border = true,
            },
        },
    })

    -- buttons render right-to-left: close (red), minimize (yellow), maximize (green)
    local function bar_button(color, action)
        hl.plugin.hyprbars.add_button({
            bg_color = "rgb(" .. color .. ")",
            fg_color = "rgb(FFFFFF)", -- unused: no icon glyphs
            size     = 13,
            icon     = "",
            action   = action,
        })
    end
    bar_button(V.re0, "hyprctl dispatch \"hl.dsp.window.close()\"")
    -- minimize/restore toggle: stash in special:minimized, or (if already there)
    -- send the window back to its origin workspace. See scripts/minimize-toggle.sh
    bar_button(V.ye0, scripts .. "/minimize-toggle.sh")
    -- maximize: fill the workspace (mode=1 keeps gaps/bar; not true fullscreen)
    bar_button(V.gr0, "hyprctl dispatch \"hl.dsp.window.fullscreen({mode=1})\"")
end
