-- Generated by nwg-displays on 2026-05-26 at 21:24:08. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@165.0",
    position = "2560x193",
    scale = 1.0
})
hl.monitor({
    output = "DP-5",
    mode = "2560x1440@279.96",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
