alias g="git"
alias gb="git branch"
alias gf="git fetch"
alias grb="git rebase"
alias ga="git add"
alias gd="git diff"
alias gst="git status"
alias gc="git commit"
alias gco="git checkout"
alias gp="git push"
alias gfgrb="git fetch && git rebase"
alias gs="git stash"
alias gsp="git stash pop"
alias grs="git restore"
alias please="git push --force-with-lease"
alias again="git commit --amend --no-edit"

